### ISSUE TITLE
Autocomplete Search

### ISSUE THREAD

**Issue by thkro** [croxton/Search_fields#4]
I am using code below for a EE 1.7 autocomplete search. Works great, but I tried to apply this to a EE2 site and get my CSS style sheet as the result. Could tell what I am doing wrong, I have modified the PHP slighty as documented. I was getting errors with the plugin but replace line 317 with $query->result_array() as suggested by another user.

Your assistance would be greatly appreciated!

EE 1.7 code

<?php
global $IN; 
$q = str_replace(array('{','}','?','\"','\'), '', trim($q = $IN->GBL('q', 'GET')));
?>  

{exp:search_fields search:title="<?php echo $_GET['q'] ?>" weblog="courses" parse="inward"}
   {exp:weblog:entries entry_id="{search_results}" weblog="courses" dynamic="off" disable="categories|trackbacks|member_data|pagination"}
       <a href="">{title}</a>|{page_uri}
    {/exp:weblog:entries}
{/exp:search_fields}

EE 2 code

<?php
 $q = str_replace(array('{','}','?','\"','\'), '', trim($q = $this->EE->input->get('q')));
?> 

{exp:search_fields search:title="<?php echo $_GET['q'] ?>" channel="courses" parse="inward"}
   {exp:channel:entries entry_id="{search_results}" channel="courses" dynamic="off" disable="categories|trackbacks|member_data|pagination"}
       <a href="">{title}</a>|{page_uri}
    {/exp:channel:entries}
{/exp:search_fields}

**Comment by croxton** [comment]
Please try replacing <?php echo $_GET['q'] ?> with an actual value that you might expect. Let me know if the plugin works.

**Comment by thkro** [comment]
Thanks for the response, added the input value and the plugin works as expected. Will have to go through the php code and see why it is not sending and receiving the value.

**Comment by thkro** [comment]
Okay I finally found the solution to the problem, just needed to adjust the input class as documented in the EE2 User Guide. A lot simpler and works great! Hopefully this will help others who get stuck.

{exp:search_fields search:title="<?php echo $this->EE->input->post('q'); ?>" channel="courses" parse="inward"}
   {exp:channel:entries entry_id="{search_results}" channel="courses" dynamic="off" disable="categories|trackbacks|member_data|pagination"}
       <a href="">{title}</a>|{page_uri}
    {/exp:channel:entries}
{/exp:search_fields}
